#!/bin/sh

## This script works in conjunction with the hmc_collect scripts. It uses it to
# create a list of available hosts from that data. It also maintains a weeks worth
# of files in the event that you want to roll back a list.

## This script should run on your Linux bastion host.

## Requires a file in your home .dsh configuration directory called machines.exclude
# This file should contain simple patterns to ignore.

HOME=/home/vjohnson
## Change the email as appropriate.
EMAIL=nobody@nobody.com
TMPFILE=/tmp/machines.list
DATESTAMP=$(date +"%Y%m%d")
LC_ALL=C

##Rebuild the hmc data collection (this execution takes some time)
$HOME/bin/hmc_collect.pl > $HOME/data/hmc_collect.$DATESTAMP.csv
if ([ -f $HOME/data/hmc_collect.csv ] | [ -L $HOME/data/hmc_collect.csv ] )
then
  rm $HOME/data/hmc_collect.csv
fi
ln -s "$HOME/data/hmc_collect.$DATESTAMP.csv" $HOME/data/hmc_collect.csv

##Keep only the last 7 versions of this file:
for i in `find $HOME/data/ -name "hmc_collect.*.csv" | sort | head -n -8`
do
  rm $i
done

##Filter the unnecessary lines (such as VIOS and only for hosts that are in the RUNNING STATE) and remove duplicates
grep aixlinux $HOME/data/hmc_collect.csv | grep Running | awk 'BEGIN { FS = ":" }; {print $3}' | sort | uniq > $TMPFILE

##Remove the excluded hosts based on the $HOME/.dsh/machines.exclude (which is a manually generated file that just has specific host rules to ignore,
## sometimes we don't want to include new hosts or a group of hosts like the oit hosts)  This file can contain comments so ignore lines that start with #
## Note: in the future add some code to handle the case of this file not existing.
for i in `grep -v ^# $HOME/.dsh/machines.exclude`
do
  grep -v $i $TMPFILE > $TMPFILE.1
  mv $TMPFILE.1 $TMPFILE
done

##Change THIS SCRIPT to something else that can be filtered in your email appropriately.
diff -c $HOME/.dsh/machines.list $TMPFILE | mailx -a "From: THIS SCRIPT" -s "machines.list rebuild process changes" $EMAIL

##Copy the temp file into its place
cp $TMPFILE $HOME/.dsh/machines.list
##I used to have to do these as well, but they're symbolic links back to the one in my home directory now.
#cp $TMPFILE /root/.dsh/machines.list
#cp $TMPFILE /etc/dsh/machines.list

##Remove any temporary files generated by this script
rm $TMPFILE
