#!/usr/bin/perl
#
# Author: Vincent Johnson
#
# The purpose of this script is to take an LPAR dump of each HMC in the @hmc_list.
# The power in this script is the data can be easily manipulated.  The output of this command can easily be redirected via standard output to a file.
# That file can then be opened with OpenOffice Spreadsheets or Excel as a ":" delimited list.  We can also manipulate the file with regular commands
#
# Exmaple.  This example takes the file generated by the output of this script to hmc_collect.data.csv  It eliminates all vios, oit servers, cuts out all but the host names
# via awk and then removes duplicate entries via uniq:
#
# grep aixlinux hmc_collect.data.csv | grep -v oit | awk 'BEGIN { FS = ":" }; {print $3}' | uniq
#
# The HMC list is the start point, we can modify this later if we want to do more.
# It's also worth noting that these are the short names only and >>THIS<< host, should be able to resolve each of these
#

## HMC host list, this line should be modified to suit your environment.
my(@hmc_list) = ("hmc01", "hmc02", "hmc03");

foreach $hmc_host (@hmc_list)
{

  ##Pull a list of frames as seen from each HMC
  foreach $frameinfo (`ssh -q $hmc_host lssyscfg -r sys -F name:state`)
  {
    chomp($frameinfo);
	($frame, $state) = split (":", $frameinfo);
	##print "$frame-_-$state";
	if ($state eq "Operating")
	{
		foreach $lpar (`ssh -q $hmc_host lssyscfg -r lpar -m $frame -F name:lpar_id:lpar_env:os_version:default_profile:curr_profile:state`)
		{
		  #Collect the CPU and Memory Data:
		  ($lparname,$other) = split (":", $lpar);
		  my($null, $proc_mode, $proc_share, $proc_unit, $proc_virt, $proc_weight)=split(":", `ssh -q $hmc_host lshwres -m $frame -r proc --level lpar -F lpar_name:curr_proc_mode:curr_sharing_mode:run_proc_units:run_procs:run_uncap_weight | grep "$lparname:"`);
		  my($null, $memmode, $memrun)=split(":", `ssh -q $hmc_host lshwres -m $frame -r mem --level lpar -F lpar_name:mem_mode:run_mem | grep "$lparname:"`);
		  chomp($lpar);
		  chomp($proc_weight);
		  print $hmc_host.":".$frame.":".$lpar.":".$proc_mode.":".$proc_share.":".$proc_unit.":".$proc_virt.":".$proc_weight.":".$memmode.":".$memrun;
		}
	}
  }
}

exit 0;
